name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux-x86_64
            artifact_name: pidgin-compiler-linux-x86_64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            platform: linux-aarch64
            artifact_name: pidgin-compiler-linux-aarch64
          - os: macos-latest
            target: x86_64-apple-darwin
            platform: macos-x86_64
            artifact_name: pidgin-compiler-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            platform: macos-aarch64
            artifact_name: pidgin-compiler-macos-aarch64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            platform: windows-x86_64
            artifact_name: pidgin-compiler-windows-x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create distribution
        run: |
          chmod +x scripts/create-distribution.sh
          ./scripts/create-distribution.sh ${{ matrix.platform }} ${{ matrix.os }}

      - name: Create zip archive
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            powershell Compress-Archive -Path "pidgin-compiler-${{ matrix.platform }}" -DestinationPath "${{ matrix.artifact_name }}.zip"
          else
            zip -r "${{ matrix.artifact_name }}.zip" "pidgin-compiler-${{ matrix.platform }}"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pidgin-compiler-linux-x86_64.zip
            pidgin-compiler-linux-aarch64.zip
            pidgin-compiler-macos-x86_64.zip
            pidgin-compiler-macos-aarch64.zip
            pidgin-compiler-windows-x86_64.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 