name: Test Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Run examples
        run: |
          cargo run examples/hello.pg
          cargo run examples/simple.pg
          cargo run examples/fibonacci.pg

      - name: Build release for testing
        run: cargo build --release

      - name: Test distribution script
        run: |
          chmod +x scripts/create-distribution.sh
          ./scripts/create-distribution.sh test-platform ubuntu-latest
          ls -la pidgin-compiler-test-platform/ 