name: Fast Feedback

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  quick-test:
    name: Quick Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build

      - name: Run unit tests
        run: cargo test

      - name: Run basic examples
        run: |
          echo "Running basic examples..."
          cargo run examples/hello.pg
          cargo run examples/simple.pg
          cargo run examples/fibonacci.pg
          echo "Basic examples completed"

      - name: Test debug modes
        run: |
          echo "Testing debug modes..."
          cargo run examples/hello.pg --tokens
          cargo run examples/hello.pg --ast
          echo "Debug modes tested"

      - name: Test REPL functionality
        run: |
          echo "Testing REPL input..."
          echo 'print "Hello from REPL";' | cargo run
          echo "REPL test completed"

      - name: Quick syntax check
        run: |
          echo "Checking syntax of key examples..."
          cargo run examples/array_test.pg
          cargo run examples/test_new_features.pg
          echo "Syntax check completed" 